{% set name = "StructuralGT" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compass-stc/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0b9a6a47c3f40d6803533fd96c21f438f8fa45e42f238b36dd7a2c53a9cefd2e

build:
  skip: true  # [py<=311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform]
    - igraph
    - eigen
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - numpy >=2.0.0
    - cython >=3.0.2
    - igraph
    - eigen
    - pip
  run:
    - python
    - scipy
    - scikit-image
    - matplotlib-base
    - networkx
    - opencv
    - pandas
    - cython
    - gsd >=3.0.0
    - python-igraph
    - igraph
    - eigen
    - pytest
    - cmake
    - freud >=3.1.0
    - ipywidgets

test:
  imports:
    - StructuralGT
    - gsd.hoomd
  requires:
    - pytest
  source_files:
    - StructuralGT/pytest
  commands:
    - pytest StructuralGT/pytest

about:
  home: https://compass.engin.umich.edu/structuralgt-software/
  repository: https://github.com/compass-stc/StructuralGT
  documentation: https://structuralgt.readthedocs.io/en/latest/
  description: |
    StructuralGT (SGT) provides a set of tools for the quantitative analysis
    of material networks, relying extensively on methods from graph theory
    (GT). The API exposes the entire data-to-network workflow combined with
    modular tools for analysis of the resulting graphs. The Python API makes
    calls to either fast C++ libraries or SGT scripts. The advanced user has
    the option to incorporate their own C++ scripts using the provided
    template wrapper. Finally, SGT writes the analyzed graphs to a
    geometry-preserving filetype allowing for easy visualization of the data
    with the OVITO desktop applicatio.
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Graph theoretic analysis of material science netwoks.

extra:
  recipe-maintainers:
    - AlainKadar
