{% set name = "StructuralGT" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compass-stc/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5ec6f70112ab6cdd7569533a7c300df6b35650786284c61b73166cbc9413b2e8

build:
  skip: true  # [py<=311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform]
    - igraph
    - eigen
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - numpy >=2.0.0rc1
    - cython >=3.0.2
    - igraph
    - eigen
    - pip
  run:
    - python
    - scipy
    - scikit-image
    - matplotlib-base
    - networkx
    - opencv
    - pandas
    - cython
    - gsd >=3.0.0
    - python-igraph
    - igraph
    - eigen
    - pytest
    - cmake
    - freud >=3.1.0
    - ipywidgets

test:
  imports:
    - StructuralGT
  commands:
    - cd /
    - pytest --pyargs structuralgt -v -ra
  requires:
    - pytest

about:
  home: https://github.com/compass-stc/{{ name }}
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Graph theoretic analysis of material science netwoks.

extra:
  recipe-maintainers:
    - AlainKadar
